name: function_confirm
description: A new Flutter project.
publish_to: "none" # pub.devに公開したい場合はこの行を削除

version: 1.0.0+1 # +以降がビルド番号

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  animations: ^2.0.2
  http: ^1.0.0
  webview_flutter: ^4.0.2

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
